# Generated by Django 6.0.1 on 2026-07-10 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_alter_expense_options_expense_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
